# Generated by Django 3.1.5 on 2021-01-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporttype', models.CharField(blank=True, db_column='ReportType', max_length=5, null=True)),
                ('transactionid', models.TextField(blank=True, db_column='TransactionID', null=True)),
                ('submitdate', models.DateField(blank=True, db_column='SubmitDate', null=True)),
                ('claim', models.FloatField(blank=True, db_column='Claim', null=True)),
                ('score', models.FloatField(blank=True, db_column='Score', null=True)),
                ('predictiondate', models.DateField(blank=True, db_column='PredictionDate', null=True)),
                ('manualintervention', models.CharField(blank=True, db_column='ManualIntervention', max_length=3, null=True)),
                ('formerlynomi', models.CharField(blank=True, db_column='FormerlyNoMI', max_length=3, null=True)),
            ],
            options={
                'db_table': 'details',
                'managed': False,
            },
        ),
    ]
